### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by dle0105** [Timmiej93/ModOverview#2]
Is there a way to increase the unload speed of the water?

Changing overload values and times in the trailer XML doesn't seem to do anything for this method of unloading, but it does affect the unload speeds of whats supported without this fix.

**Comment by Timmiej93** [comment]
I assume you're talking about the WaterTrailerFix mod? If so, please open an issue on that specific mod the next time. The bit in my bio here on GitHub (Contact: Either open an issue on my repo "ModOverview", or send me a message on Discord: Timmiej93#9702) is meant for contact in general, not for issues with specific mods.

That being said: If you want to empty a water trailer quicker, you need to go into `FS17_T93_WaterTrailerFix/scripts/WaterTrailerFix.lua`, line 54 ([click](https://github.com/Timmiej93/FS17_T93_WaterTrailerFix/blob/ddd284c4289f35507868f7499f029586f498b2c4/scripts/WaterTrailerFix.lua#L54)) and change the number `100`. This is the number of seconds it will take to empty the trailer, so setting it to a lower number empties the trailer quicker.

**Comment by dle0105** [comment]
> 
> 
> I assume you're talking about the WaterTrailerFix mod? If so, please open an issue on that specific mod the next time. The bit in my bio here on GitHub (Contact: Either open an issue on my repo "ModOverview", or send me a message on Discord: Timmiej93#9702) is meant for contact in general, not for issues with specific mods.
> 
> That being said: If you want to empty a water trailer quicker, you need to go into `FS17_T93_WaterTrailerFix/scripts/WaterTrailerFix.lua`, line 54 ([click](https://github.com/Timmiej93/FS17_T93_WaterTrailerFix/blob/ddd284c4289f35507868f7499f029586f498b2c4/scripts/WaterTrailerFix.lua#L54)) and change the number `100`. This is the number of seconds it will take to empty the trailer, so setting it to a lower number empties the trailer quicker.

Whoops, my bad.

Thanks for the reply and sorry for being in the wrong place.

**Comment by Timmiej93** [comment]
No worries, it happens. Let me know if this fixes your issue, since I'm not 100% sure if I'm remembering everything correctly.

**Comment by dle0105** [comment]
> 
> 
> No worries, it happens. Let me know if this fixes your issue, since I'm not 100% sure if I'm remembering everything correctly.

Yep, that did the trick! Thanks a bunch for your help and the mod!
